<img src='../../../common/DH_LOGO.jpeg' align='left' width=100%/>

In [1]:
# initial setup
#%run "../../../common/0_notebooks_base_setup.py"

# DHDSPaDM3A22 - Prática Guiada: Variáveis Fictícias (Dummies).

# Dummies

### Introdução

Variáveis ​​fictícias ou "dummies" são freqüentemente usadas ​​em conjuntos de dados para ajudar a colocar números em objetos categóricos. Muitas vezes, quando os cientistas de dados analisam os dados, eles têm a tarefa de decompor os dados em objetos que podem ser modelados. Embora seja possível modelar objetos escritos, existem muitos objetos que só podem ser modelados com números.

Como futuros cientistas de dados, é fundamental criar números a partir de valores categóricos corretamente.

Ao treinar um modelo de aprendizado de máquina, é necessário transformar e codificar as variáveis ​​de tipo categórico. Existem dois tipos de variáveis ​​categóricas:

- [Nominal](https://www.questionpro.com/blog/nominal-ordinal-interval-ratio/). Uma variável pode ser tratada como nominal quando seus valores representam categorias que não obedecem a uma classificação intrínseca. Por exemplo, o departamento da empresa onde um funcionário trabalha. Alguns exemplos de variáveis nominais são: região, código postal ou denominação religiosa.

- [Ordinal](https://www.questionpro.com/blog/ordinal-data/). Uma variável pode ser tratada como ordinal quando seus valores representam categorias com alguma classificação intrínseca. Por exemplo, níveis de satisfação com um serviço, variando de muito insatisfeito a muito satisfeito. Exemplos de variáveis ordinais incluem escalas de atitude que representam o grau de satisfação ou confiança e pontuações de avaliação de preferência.

[<img src="img/variable_types.png" align='center' width=60% width="400" height="200" align='center'>](http://digitalhouse.com.ar/)

Aprenderemos a codificar ambas as classes neste notebook.

### Sobre o conjunto de dados.

Começaremos carregando um conjunto de dados do [Titanic](https://towardsdatascience.com/machine-learning-with-the-titanic-dataset-7f6909e58280). Este é um conjunto de dados muito pequeno que consiste em dados sobre variáveis ​​demográficas dos passageiros da embarcação emblemática, classificados por gênero, faixa de preço do bilhete, etc.

## Variáveis Categóricas Nominais:

In [2]:
import pandas as pd

# carregamos o dataset 
df = pd.read_csv('../Data/Titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Podemos obter as variáveis `dummies` para a coluna "sexo" onde ela só pode ter dois valores possíveis: masculino ou feminino. As variáveis `dummy` obtidas representam o estado da variável categórica (presença / ausência) da mesma. Usando a função [`pandas.get_dummies()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html) do pandas:

### Método 1. Pandas get_dummies

In [4]:
dummy = pd.get_dummies(df['Sex'])
dummy.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [5]:
# concatenamos ambos os datasets 
df = pd.concat([df, dummy], 
               axis = 1
              )

df['Survived'] = df.Survived.apply(lambda x: 'yes' if x == 1 else 'No')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,0
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,0
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1

### Método 2. `sklearn.preprocessing.OneHotEncoder`

A entrada para a função  [`Sklearn.preprocessing.OneHotEncoder()`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) deve ser semelhante a uma matriz de inteiros ou `strings`, denotando os valores assumidos por `features` categóricas (discretas). Os recursos são codificados usando um esquema de [codificação `one-hot`](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (também conhecido como `one-of-K` ou `dummy`). Isso cria uma coluna binária para cada categoria e retorna uma matriz esparsa ou matriz densa (dependendo do parâmetro esparso).

Podemos ajustar esse objeto no conjunto de treino e, em seguida, usar o mesmo objeto para transformar o conjunto de teste. Por outro lado, pd.get_dummies retorna "dataframe" com codificações baseadas nos valores do "dataframe" que passamos para ele. Isso pode ser bom para uma análise rápida, mas para um projeto que mais tarde teríamos que colocar em produção, é melhor ter o objeto OneHotEncoder para que possamos "transformar" mais tarde os novos dados que chegam ao nosso servidor.

In [7]:
from sklearn.preprocessing import OneHotEncoder 
onehot_encoder = OneHotEncoder(handle_unknown = 'ignore')

#Ajustamos e transformamos a coluna "sex"
dummy_oneHot = onehot_encoder.fit_transform(df[['Sex']])

#Colocamos um vetor no conjunto de dados

dummy_oneHot = pd.DataFrame(dummy_oneHot.toarray(), 
                            columns = df['Sex'].unique()
                           )
dummy_oneHot.head()

   male  female
0   0.0     1.0
1   1.0     0.0
2   1.0     0.0
3   1.0     0.0
4   0.0     1.0

### Variáveis `dummies` e Multicolinearidade.

A variável fictícia "trap" se manifesta diretamente a partir de uma codificação `One-hot` aplicada a variáveis categóricas. Conforme discutido anteriormente (suposições de regressão linear), o tamanho dos vetores de uma codificação `one-Hot` é igual ao número de valores exclusivos que uma coluna categórica pode assumir. Vamos imaginar a velocidade variável com $3$ níveis: 


$[1]: speed_{low} + speed_{Medium} + speed_{High} = 1$


A partir da relação acima, podemos expressar qualquer uma das três variáveis independentes em termos das outras duas, vamos pegar $ speed_{low} $ e expressá-la em termos de $ speed_ {medium} $ e $ speed_ {high} $:

$[2]: speed_{low} = 1 - speed_{Medium} - speed_{High}$

### Porque isso não é bom?

Como discutimos anteriormente, isso tem uma implicação direta no problema de regressão linear.

Podemos substituir speed_low na equação [1] por seu valor na equação [1]. Na verdade, isso significa que (pelo menos) um dos recursos com os quais estamos trabalhando é **redundante**; essa característica pode ser qualquer uma das três, já que a equação 2 pode ser escrita com qualquer uma delas. Portanto, estamos fazendo nosso modelo aprender um peso adicional que não é realmente necessário. Isso consome tempo e energia computacional. Isso também fornece uma meta de otimização que pode não ser muito razoável e também pode ser difícil de trabalhar.

### Como resolvemos isso?

Como a codificação `One-Hot` induz multicolinearidade perfeita, removemos uma das colunas da features codificada. Por exemplo, podemos escolher descartar $ speed_{medium} $ ou em nosso exemplo "masculino" embora a escolha seja completamente arbitrária.

- Quando usamos [`pandas.get_dummies()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), podemos passar um argumento adicional, `drop_first = True` para eliminar a primeira nova coluna que obtivermos após a codificação.

In [8]:
dummy_correct = pd.get_dummies(df['Sex'], 
                               drop_first = True
                              )
dummy_correct.head()

   male
0     1
1     0
2     0
3     0
4     1

Quando usamos `sklearn.preprocessing.OneHotEncoder()` e queremos descartar uma das novas colunas, passamos o argumento do construtor `drop = 'first'` da classe `OneHotEncoder`.

In [9]:
from sklearn.preprocessing import OneHotEncoder 
onehot_encoder2 = OneHotEncoder(drop = 'first')

#Ajustamos e transformamos a coluna "sex"
dummy_oneHot_correct = onehot_encoder2.fit_transform(df[['Sex']])

#Colocamos um vetor no conjunto de dados

dummy_oneHot_correct = pd.DataFrame(dummy_oneHot_correct.toarray())
dummy_oneHot_correct.head()

     0
0  1.0
1  0.0
2  0.0
3  0.0
4  1.0

## Variáveis categóricas Ordinais

Usaremos as variáveis `Survived` para gerar uma variável derivada que leva em consideração que se sobreviveu é "melhor" do que se não sobreviveu. Com isso podemos gerar, por exemplo, uma variável categórica que pode ser usada como um vetor `target` em um problema de classificação.

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['Survived'])

### Conclusões:

Ao treinar um modelo de aprendizado de máquina, é necessário transformar e codificar as variáveis categóricas.


- [Benchmarking Categorical Encoders](https://towardsdatascience.com/benchmarking-categorical-encoders-9c322bd77ee8)